### ISSUE TITLE
Build failure under gradle.

### ISSUE THREAD

**Issue by emacstheviking** [Phosphorus15/intellij-prolog#24]
I am trying to get a local build but I have a failure that I don't understand, the error output is as follows, I am on Linux Mint, uname -a:
```
╰─$ ./gradlew tasks --scan
FAILURE: Build failed with an exception.
* Where:
Build file '/home/sean/Documents/code/java/intellij/intellij-prolog/build.gradle' line: 52

* What went wrong:
A problem occurred evaluating root project 'intellij-prolog'.
> Could not get unknown property 'intellijPublishToken' for task ':publishPlugin' of type org.jetbrains.intellij.tasks.PublishTask.
```
I have created a build scan here: (hope it's visible)

https://scans.gradle.com/s/ak6k3e6wj5bbm/failure?openFailures=WzBd&openStackTraces=WzEsMF0#top=0

**Comment by Phosphorus15** [comment]
glad that I put an end on this issue, now a build can be completed without hindrance

**Comment by emacstheviking** [comment]
I still have a build issue, the fix removed my original reported problem but the output from "./gradlew build" is this... have I omitted a build step or some other pre-build process?

```
╰─$ ./gradlew build

> Task :compileScala
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/annotator/external-annotator.scala:73: not found: type PrologToplevelExpr
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/annotator/external-annotator.scala:73: not found: type PrologTrailingExpr
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/annotator/external-annotator.scala:73: not found: type PrologPredicate
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/annotator/external-annotator.scala:73: not found: type PrologExprHead
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/annotator/external-annotator.scala:73: not found: type PrologExprBody
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/annotator/singleton-annotator.scala:6: object PrologToplevelExpr is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/annotator/singleton-annotator.scala:10: not found: type PrologToplevelExpr
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/annotator/singleton-annotator.scala:10: not found: type PrologTrailingExpr
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/completion/atom-completion.scala:7: object PrologToplevelExpr is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/completion/atom-completion.scala:15: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/completion/atom-completion.scala:18: not found: type PrologToplevelExpr
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/completion/atom-completion.scala:19: not found: type PrologTrailingExpr
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/completion/completion.scala:7: object PrologTypes is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/completion/completion.scala:8: object impl is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/completion/completion.scala:18: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/completion/completion.scala:25: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/completion/predicate-completion.scala:9: object PrologPredicateId is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/toolchain/stub-elements.scala:7: object PrologPredicateId is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/toolchain/stub-elements.scala:26: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/completion/predicate-completion.scala:19: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/inspector/singleton-analysis.scala:5: object PrologIdent is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/inspector/singleton-analysis.scala:10: not found: type PrologIdent
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/inspector/singleton-analysis.scala:10: value getAtomId is not a member of com.intellij.psi.PsiElement
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/parser-defs.scala:8: object PrologParser is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/parser-defs.scala:12: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/parser-defs.scala:12: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/parser-defs.scala:21: not found: type PrologParser
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/parser-defs.scala:29: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/project/run-config-simple.scala:10: object PrologRefPredicateId is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/project/run-config-simple.scala:32: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/project/run-config-simple.scala:33: not found: type PrologRefPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/project/run-config-simple.scala:34: not found: type PrologTrailingExpr
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/toolchain/stub-elements.scala:29: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/psi/decl-mixin.scala:33: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/psi/decl-mixin.scala:33: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/psi/param-list-mixin.scala:11: not found: type PrologLogicalAnd
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/psi/param-list-mixin.scala:12: not found: type PrologEquivBinary
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/psi/param-list-mixin.scala:14: not found: type PrologEquivBinary
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/psi/param-list-mixin.scala:14: missing argument list for method recursiveFindShallow in class PrologParameterListMixin
Unapplied methods are only converted to functions when a function type is expected.
You can make this conversion explicit by writing `recursiveFindShallow _` or `recursiveFindShallow(_)` instead of `recursiveFindShallow`.
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/psi/param-list-mixin.scala:20: not found: type PrologEquivBinary
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/psi/param-list-mixin.scala:20: value map is not a member of Array[T with Object]
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/psi/reference-mixin.scala:29: not found: type PrologToplevelExpr
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/psi/reference-mixin.scala:30: not found: type PrologTrailingExpr
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/psi/reference-mixin.scala:97: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/toolchain/stub-elements.scala:37: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/references/goto-decl-handler.scala:9: object impl is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/references/goto-decl-handler.scala:10: object PrologPredicateId is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/references/goto-decl-handler.scala:20: not found: type PrologRefPredicateIdImpl
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/references/goto-decl-handler.scala:21: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/references/goto-decl-handler.scala:22: value multiResolve is not a member of com.intellij.psi.PsiElement
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/references/goto-pred-contributor.scala:7: object PrologPredicateId is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/references/goto-pred-contributor.scala:16: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:13: object PrologTypes is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:15: not found: type PrologLexer
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:22: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:22: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:24: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:26: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:26: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:26: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:28: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:28: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:28: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:28: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:30: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:32: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:34: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:34: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:34: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:36: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:38: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:38: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:52: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:52: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:53: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala:53: not found: value PrologTypes
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/toolchain/stub-elements.scala:8: object impl is not a member of package tech.phosphorus.intellij.prolog.psi
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/toolchain/stub-elements.scala:18: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/toolchain/stub-elements.scala:19: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/toolchain/stub-elements.scala:33: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/toolchain/stub-elements.scala:39: not found: type PrologPredicateId
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/toolchain/stub-elements.scala:39: not found: type PrologPredicateIdImpl
[Error] /home/sean/Documents/code/java/intellij/intellij-prolog/src/main/scala/tech/phosphorus/intellij/prolog/toolchain/stub-elements.scala:41: not found: type PrologPredicateId
83 errors found

> Task :compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> Compilation failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 12s
1 actionable task: 1 executed

```

**Comment by Phosphorus15** [comment]
run `gradle generatePrologLexer` and `gradle generatePrologParser` before an entire build (cheer up ! just one step further :P )

**Comment by Phosphorus15** [comment]
@ice1000 is there a way making these two commands run before the first build ?

**Comment by emacstheviking** [comment]
OK @Phosphorus15  I ran those two tasks first and then it moved on a bit...
```
╰─$ ./gradlew build               

> Task :buildSearchableOptions
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to field java.awt.event.InvocationEvent.runnable
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-04-30 14:53:27,955 [   2681]   WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options 
Starting searchable options index builder
2020-04-30 14:53:30,207 [   4933]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
2020-04-30 14:53:34,954 [   9680]   WARN - Container.ComponentManagerImpl - Do not use constructor injection (requestorClass=com.android.tools.idea.sdk.AndroidSdks) 
Searchable options index builder failed
java.nio.file.NoSuchFileException: /usr/bin/../library
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixPath.toRealPath(UnixPath.java:860)
        at tech.phosphorus.intellij.prolog.toolchain.PrologToolchain$$anonfun$stdlibPath$1.apply(toolchain.scala:44)
        at tech.phosphorus.intellij.prolog.toolchain.PrologToolchain$$anonfun$stdlibPath$1.apply(toolchain.scala:44)
        at scala.Option.getOrElse(Option.scala:121)
        at tech.phosphorus.intellij.prolog.toolchain.PrologToolchain.stdlibPath(toolchain.scala:44)
        at tech.phosphorus.intellij.prolog.toolchain.PrologToolchain$.instanceLibrary(toolchain.scala:108)
        at tech.phosphorus.intellij.prolog.settings.LanguageConfigurable.createComponent(config.scala:28)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:162)
        at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:77)
        at com.intellij.ide.ui.search.SearchUtil.processProjectConfigurables(SearchUtil.java:49)
        at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:97)
        at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:80)
        at com.intellij.openapi.application.ApplicationStarter.main(ApplicationStarter.java:62)
        at com.intellij.idea.ApplicationLoader$startApp$8$1$1.run(ApplicationLoader.kt:228)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
        at com.intellij.idea.ApplicationLoader$startApp$8$1.run(ApplicationLoader.kt:227)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
        at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
        at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

> Task :buildSearchableOptions FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSearchableOptions'.
> Process 'command '/home/sean/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_6-linux-x64-b765.25/jbr/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 37s
8 actionable tasks: 2 executed, 6 up-to-date
```

**Comment by Phosphorus15** [comment]
`buildSearchableoOptions` is a complex task and should only be run before generating a releases, if you want to debug the plugin, simply use `gradle runIde`

**Comment by Phosphorus15** [comment]
But these error messages do exposed something wrong with prolog-stdlib indexing , that is, assume that the library is relative to location of `swipl` binary.

**Comment by ice1000** [comment]
`buildSrc` is a thing.
